import {solution} from "./pairCoder/pairCoderFunc";

solution('dfihunjkroieriolkngldfnoirtisklsknriutrpojslnxvlspiroeuhkgfdkjwmwermskdufiuhksbmnafkjmbzuxygewouinkegjnskngxcnljgajdhouhnamxcnvexmvjgsfgsg');
